# frozen_string_literal: true

require "rails_helper"

RSpec.describe SupplyChain::QuestionnaireResponse, type: :model do
  let(:account) { create(:account) }
  let(:vendor) { create(:supply_chain_vendor, account: account) }
  let(:template) { create(:supply_chain_questionnaire_template, account: account) }
  let(:user) { create(:user, account: account) }

  describe "associations" do
    it { is_expected.to belong_to(:vendor).class_name("SupplyChain::Vendor") }
    it { is_expected.to belong_to(:template).class_name("SupplyChain::QuestionnaireTemplate") }
    it { is_expected.to belong_to(:account) }
    it { is_expected.to belong_to(:risk_assessment).class_name("SupplyChain::RiskAssessment").optional }
    it { is_expected.to belong_to(:requested_by).class_name("User").optional }
    it { is_expected.to belong_to(:reviewed_by).class_name("User").optional }
  end

  describe "validations" do
    subject { build(:supply_chain_questionnaire_response, vendor: vendor, template: template, account: account) }

    it { is_expected.to validate_presence_of(:status) }
    it { is_expected.to validate_inclusion_of(:status).in_array(SupplyChain::QuestionnaireResponse::STATUSES) }

    # Note: access_token is auto-generated by before_validation callback,
    # so shoulda-matchers can't test presence directly
    it "requires access_token" do
      response = create(:supply_chain_questionnaire_response, vendor: vendor, template: template, account: account)
      response.access_token = nil
      expect(response).not_to be_valid
      expect(response.errors[:access_token]).to include("can't be blank")
    end

    it "validates uniqueness of access_token" do
      first = create(:supply_chain_questionnaire_response, vendor: vendor, template: template, account: account)
      duplicate = build(:supply_chain_questionnaire_response, vendor: vendor, template: template, account: account)
      duplicate.access_token = first.access_token
      expect(duplicate).not_to be_valid
      expect(duplicate.errors[:access_token]).to include("has already been taken")
    end
  end

  describe "scopes" do
    let!(:pending_response) { create(:supply_chain_questionnaire_response, vendor: vendor, template: template, account: account, status: "pending") }
    let!(:in_progress_response) { create(:supply_chain_questionnaire_response, vendor: vendor, template: template, account: account, status: "in_progress") }
    let!(:submitted_response) { create(:supply_chain_questionnaire_response, vendor: vendor, template: template, account: account, status: "submitted") }
    let!(:reviewed_response) { create(:supply_chain_questionnaire_response, vendor: vendor, template: template, account: account, status: "reviewed") }
    let!(:expired_response) { create(:supply_chain_questionnaire_response, vendor: vendor, template: template, account: account, status: "expired") }
    let!(:expiring_soon_response) { create(:supply_chain_questionnaire_response, vendor: vendor, template: template, account: account, expires_at: 3.days.from_now) }
    let!(:not_expiring_response) { create(:supply_chain_questionnaire_response, vendor: vendor, template: template, account: account, expires_at: 30.days.from_now) }

    it "filters by status" do
      expect(described_class.by_status("pending")).to include(pending_response)
      expect(described_class.by_status("pending")).not_to include(submitted_response)
    end

    it "filters pending responses" do
      expect(described_class.pending).to include(pending_response)
    end

    it "filters in_progress responses" do
      expect(described_class.in_progress).to include(in_progress_response)
    end

    it "filters submitted responses" do
      expect(described_class.submitted).to include(submitted_response)
    end

    it "filters reviewed responses" do
      expect(described_class.reviewed).to include(reviewed_response)
    end

    it "filters expired responses" do
      expect(described_class.expired).to include(expired_response)
    end

    it "filters awaiting_response" do
      expect(described_class.awaiting_response).to include(pending_response, in_progress_response)
      expect(described_class.awaiting_response).not_to include(submitted_response, reviewed_response)
    end

    it "filters needs_review" do
      expect(described_class.needs_review).to include(submitted_response)
      expect(described_class.needs_review).not_to include(pending_response)
    end

    it "filters expiring_soon" do
      expect(described_class.expiring_soon(7)).to include(expiring_soon_response)
      expect(described_class.expiring_soon(7)).not_to include(not_expiring_response)
    end

    it "filters for_vendor" do
      other_vendor = create(:supply_chain_vendor, account: account)
      other_response = create(:supply_chain_questionnaire_response, vendor: other_vendor, template: template, account: account)

      expect(described_class.for_vendor(vendor.id)).to include(pending_response)
      expect(described_class.for_vendor(vendor.id)).not_to include(other_response)
    end
  end

  describe "status predicates" do
    it "#pending? returns true for pending status" do
      response = build(:supply_chain_questionnaire_response, status: "pending")
      expect(response.pending?).to be true
    end

    it "#in_progress? returns true for in_progress status" do
      response = build(:supply_chain_questionnaire_response, status: "in_progress")
      expect(response.in_progress?).to be true
    end

    it "#submitted? returns true for submitted status" do
      response = build(:supply_chain_questionnaire_response, status: "submitted")
      expect(response.submitted?).to be true
    end

    it "#reviewed? returns true for reviewed status" do
      response = build(:supply_chain_questionnaire_response, status: "reviewed")
      expect(response.reviewed?).to be true
    end

    it "#expired? returns true for expired status" do
      response = build(:supply_chain_questionnaire_response, status: "expired")
      expect(response.expired?).to be true
    end

    it "#expired? returns true when expires_at is in the past" do
      response = build(:supply_chain_questionnaire_response, status: "pending", expires_at: 1.day.ago)
      expect(response.expired?).to be true
    end
  end

  describe "#awaiting_response?" do
    it "returns true for pending status" do
      response = build(:supply_chain_questionnaire_response, status: "pending")
      expect(response.awaiting_response?).to be true
    end

    it "returns true for in_progress status" do
      response = build(:supply_chain_questionnaire_response, status: "in_progress")
      expect(response.awaiting_response?).to be true
    end

    it "returns false for submitted status" do
      response = build(:supply_chain_questionnaire_response, status: "submitted")
      expect(response.awaiting_response?).to be false
    end
  end

  describe "#can_edit?" do
    it "returns true when awaiting and not expired" do
      response = build(:supply_chain_questionnaire_response, status: "pending", expires_at: 30.days.from_now)
      expect(response.can_edit?).to be true
    end

    it "returns false when submitted" do
      response = build(:supply_chain_questionnaire_response, status: "submitted")
      expect(response.can_edit?).to be false
    end

    it "returns false when expired" do
      response = build(:supply_chain_questionnaire_response, status: "pending", expires_at: 1.day.ago)
      expect(response.can_edit?).to be false
    end
  end

  describe "completion tracking" do
    let(:template_with_questions) do
      create(:supply_chain_questionnaire_template,
             account: account,
             questions: [
               { "id" => "q1", "section_id" => "s1", "text" => "Q1?", "required" => true },
               { "id" => "q2", "section_id" => "s1", "text" => "Q2?", "required" => true },
               { "id" => "q3", "section_id" => "s1", "text" => "Q3?", "required" => false }
             ])
    end

    describe "#completion_percentage" do
      it "calculates percentage of answered questions" do
        response = create(:supply_chain_questionnaire_response,
                         vendor: vendor,
                         template: template_with_questions,
                         account: account,
                         responses: { "q1" => { "answer" => "yes" } })
        expect(response.completion_percentage).to be_within(0.1).of(33.3)
      end

      it "returns 0 when no questions answered" do
        response = create(:supply_chain_questionnaire_response,
                         vendor: vendor,
                         template: template_with_questions,
                         account: account,
                         responses: {})
        expect(response.completion_percentage).to eq(0)
      end

      it "returns 0 when template has no questions" do
        empty_template = create(:supply_chain_questionnaire_template, account: account, questions: [])
        response = create(:supply_chain_questionnaire_response,
                         vendor: vendor,
                         template: empty_template,
                         account: account)
        expect(response.completion_percentage).to eq(0)
      end
    end

    describe "#response_count" do
      it "returns number of answered questions" do
        response = create(:supply_chain_questionnaire_response,
                         vendor: vendor,
                         template: template,
                         account: account,
                         responses: { "q1" => {}, "q2" => {} })
        expect(response.response_count).to eq(2)
      end
    end

    describe "#unanswered_questions" do
      it "returns questions without responses" do
        response = create(:supply_chain_questionnaire_response,
                         vendor: vendor,
                         template: template_with_questions,
                         account: account,
                         responses: { "q1" => { "answer" => "yes" } })
        unanswered = response.unanswered_questions
        expect(unanswered.length).to eq(2)
        expect(unanswered.map { |q| q["id"] }).to contain_exactly("q2", "q3")
      end
    end

    describe "#required_unanswered" do
      it "returns only required unanswered questions" do
        response = create(:supply_chain_questionnaire_response,
                         vendor: vendor,
                         template: template_with_questions,
                         account: account,
                         responses: { "q1" => { "answer" => "yes" } })
        required_unanswered = response.required_unanswered
        expect(required_unanswered.length).to eq(1)
        expect(required_unanswered.first["id"]).to eq("q2")
      end
    end

    describe "#all_required_answered?" do
      it "returns true when all required questions are answered" do
        response = create(:supply_chain_questionnaire_response,
                         vendor: vendor,
                         template: template_with_questions,
                         account: account,
                         responses: { "q1" => { "answer" => "yes" }, "q2" => { "answer" => "no" } })
        expect(response.all_required_answered?).to be true
      end

      it "returns false when required questions are missing" do
        response = create(:supply_chain_questionnaire_response,
                         vendor: vendor,
                         template: template_with_questions,
                         account: account,
                         responses: { "q1" => { "answer" => "yes" } })
        expect(response.all_required_answered?).to be false
      end
    end
  end

  describe "response management" do
    let(:response) { create(:supply_chain_questionnaire_response, vendor: vendor, template: template, account: account, status: "pending", responses: {}) }

    describe "#get_response" do
      it "returns response for question" do
        response.update!(responses: { "q1" => { "answer" => "yes" } })
        expect(response.get_response("q1")).to eq({ "answer" => "yes" })
      end

      it "returns nil for unanswered question" do
        expect(response.get_response("q1")).to be_nil
      end
    end

    describe "#set_response" do
      it "sets response for question" do
        response.set_response("q1", "yes")
        expect(response.responses["q1"]["answer"]).to eq("yes")
      end

      it "records answered_at timestamp" do
        response.set_response("q1", "yes")
        expect(response.responses["q1"]["answered_at"]).to be_present
      end

      it "changes status to in_progress if pending" do
        response.set_response("q1", "yes")
        expect(response.status).to eq("in_progress")
      end

      it "sets started_at when first response is added" do
        response.set_response("q1", "yes")
        expect(response.started_at).to be_present
      end
    end
  end

  describe "state transitions" do
    describe "#send_to_vendor!" do
      let(:response) { create(:supply_chain_questionnaire_response, vendor: vendor, template: template, account: account, sent_at: nil) }

      it "sets sent_at timestamp" do
        response.send_to_vendor!
        expect(response.sent_at).to be_present
      end
    end

    describe "#start!" do
      let(:response) { create(:supply_chain_questionnaire_response, vendor: vendor, template: template, account: account, status: "pending") }

      it "changes status to in_progress" do
        response.start!
        expect(response.status).to eq("in_progress")
      end

      it "sets started_at" do
        response.start!
        expect(response.started_at).to be_present
      end
    end

    describe "#submit!" do
      let(:template_with_questions) do
        create(:supply_chain_questionnaire_template,
               account: account,
               sections: [ { "id" => "s1", "weight" => 1.0 } ],
               questions: [
                 { "id" => "q1", "section_id" => "s1", "text" => "Q1?", "type" => "yes_no", "required" => true }
               ])
      end

      context "when all required questions answered" do
        let(:response) do
          create(:supply_chain_questionnaire_response,
                 vendor: vendor,
                 template: template_with_questions,
                 account: account,
                 status: "in_progress",
                 responses: { "q1" => { "answer" => "yes" } })
        end

        it "changes status to submitted" do
          response.submit!
          expect(response.status).to eq("submitted")
        end

        it "sets submitted_at" do
          response.submit!
          expect(response.submitted_at).to be_present
        end

        it "returns true" do
          expect(response.submit!).to be true
        end
      end

      context "when required questions missing" do
        let(:response) do
          create(:supply_chain_questionnaire_response,
                 vendor: vendor,
                 template: template_with_questions,
                 account: account,
                 status: "in_progress",
                 responses: {})
        end

        it "returns false" do
          expect(response.submit!).to be false
        end

        it "does not change status" do
          response.submit!
          expect(response.status).to eq("in_progress")
        end
      end
    end

    describe "#review!" do
      let(:response) { create(:supply_chain_questionnaire_response, vendor: vendor, template: template, account: account, status: "submitted") }

      it "changes status to reviewed" do
        response.review!(user, notes: "Approved")
        expect(response.status).to eq("reviewed")
      end

      it "sets reviewed_by" do
        response.review!(user)
        expect(response.reviewed_by).to eq(user)
      end

      it "sets reviewed_at" do
        response.review!(user)
        expect(response.reviewed_at).to be_present
      end

      it "sets review_notes" do
        response.review!(user, notes: "Looks good")
        expect(response.review_notes).to eq("Looks good")
      end
    end

    describe "#expire!" do
      let(:response) { create(:supply_chain_questionnaire_response, vendor: vendor, template: template, account: account, status: "pending") }

      it "changes status to expired" do
        response.expire!
        expect(response.status).to eq("expired")
      end
    end

    describe "#extend_deadline!" do
      let(:response) { create(:supply_chain_questionnaire_response, vendor: vendor, template: template, account: account, expires_at: 10.days.from_now) }

      it "extends expires_at by specified days" do
        original_expiry = response.expires_at
        response.extend_deadline!(7)
        expect(response.expires_at).to be_within(1.second).of(original_expiry + 7.days)
      end
    end
  end

  describe "#days_until_expiry" do
    it "returns days until expiry" do
      response = build(:supply_chain_questionnaire_response, expires_at: 10.days.from_now)
      expect(response.days_until_expiry).to be_within(1).of(10)
    end

    it "returns nil when no expiry" do
      response = build(:supply_chain_questionnaire_response, expires_at: nil)
      expect(response.days_until_expiry).to be_nil
    end
  end

  describe "#public_url" do
    let(:response) { create(:supply_chain_questionnaire_response, vendor: vendor, template: template, account: account) }

    it "returns URL with access token" do
      expect(response.public_url).to eq("/questionnaires/respond/#{response.access_token}")
    end
  end

  describe "#summary" do
    let(:response) { create(:supply_chain_questionnaire_response, vendor: vendor, template: template, account: account) }

    it "returns expected keys" do
      summary = response.summary

      expect(summary).to include(
        :id,
        :vendor_id,
        :vendor_name,
        :template_id,
        :template_name,
        :template_type,
        :status,
        :completion_percentage,
        :response_count,
        :total_questions,
        :overall_score,
        :sent_at,
        :started_at,
        :submitted_at,
        :reviewed_at,
        :expires_at,
        :days_until_expiry,
        :created_at
      )
    end
  end

  describe "#detailed_response" do
    let(:response) { create(:supply_chain_questionnaire_response, vendor: vendor, template: template, account: account) }

    it "returns summary, template, responses, and scores" do
      detailed = response.detailed_response

      expect(detailed).to include(:summary, :template, :responses, :section_scores, :review_notes)
    end
  end

  describe "callbacks" do
    describe "generate_access_token" do
      it "generates access_token on create" do
        response = build(:supply_chain_questionnaire_response, vendor: vendor, template: template, account: account, access_token: nil)
        response.save!
        expect(response.access_token).to be_present
      end

      it "does not override existing token" do
        response = build(:supply_chain_questionnaire_response, vendor: vendor, template: template, account: account, access_token: "existing_token")
        response.save!
        expect(response.access_token).to eq("existing_token")
      end
    end
  end

  describe "JSONB sanitization" do
    it "initializes responses as empty hash" do
      response = create(:supply_chain_questionnaire_response, vendor: vendor, template: template, account: account, responses: nil)
      expect(response.responses).to eq({})
    end

    it "initializes section_scores as empty hash" do
      response = create(:supply_chain_questionnaire_response, vendor: vendor, template: template, account: account, section_scores: nil)
      expect(response.section_scores).to eq({})
    end

    it "initializes metadata as empty hash" do
      response = create(:supply_chain_questionnaire_response, vendor: vendor, template: template, account: account, metadata: nil)
      expect(response.metadata).to eq({})
    end
  end
end
