# frozen_string_literal: true

require "rails_helper"

RSpec.describe SupplyChain::ScanExecution, type: :model do
  include ActiveSupport::Testing::TimeHelpers

  let(:account) { create(:account) }
  let(:scan_template) { create(:supply_chain_scan_template) }
  let(:scan_instance) { create(:supply_chain_scan_instance, account: account, scan_template: scan_template) }
  let(:triggered_by_user) { create(:user) }

  # ============================================
  # Constants
  # ============================================
  describe "constants" do
    it "defines STATUSES" do
      expect(SupplyChain::ScanExecution::STATUSES).to eq(%w[pending running completed failed cancelled])
    end

    it "defines TRIGGER_TYPES" do
      expect(SupplyChain::ScanExecution::TRIGGER_TYPES).to eq(%w[manual scheduled webhook pipeline api])
    end
  end

  # ============================================
  # Associations
  # ============================================
  describe "associations" do
    it { is_expected.to belong_to(:scan_instance).class_name("SupplyChain::ScanInstance") }
    it { is_expected.to belong_to(:account) }
    it { is_expected.to belong_to(:triggered_by).class_name("User").optional }
  end

  # ============================================
  # Validations
  # ============================================
  describe "validations" do
    subject { build(:supply_chain_scan_execution, scan_instance: scan_instance, account: account) }

    # Note: execution_id is auto-generated by before_validation callback,
    # so shoulda-matchers can't test presence directly
    it "requires execution_id" do
      execution = create(:supply_chain_scan_execution, scan_instance: scan_instance, account: account)
      execution.execution_id = nil
      expect(execution).not_to be_valid
      expect(execution.errors[:execution_id]).to include("can't be blank")
    end

    it "validates uniqueness of execution_id" do
      first = create(:supply_chain_scan_execution, scan_instance: scan_instance, account: account)
      duplicate = build(:supply_chain_scan_execution, scan_instance: scan_instance, account: account, execution_id: first.execution_id)
      expect(duplicate).not_to be_valid
      expect(duplicate.errors[:execution_id]).to include("has already been taken")
    end

    it { is_expected.to validate_presence_of(:status) }
    it { is_expected.to validate_inclusion_of(:status).in_array(SupplyChain::ScanExecution::STATUSES) }
    it { is_expected.to validate_presence_of(:trigger_type) }
    it { is_expected.to validate_inclusion_of(:trigger_type).in_array(SupplyChain::ScanExecution::TRIGGER_TYPES) }
  end

  # ============================================
  # Scopes
  # ============================================
  describe "scopes" do
    let!(:pending_execution) do
      create(:supply_chain_scan_execution, scan_instance: scan_instance, account: account, status: "pending")
    end
    let!(:running_execution) do
      create(:supply_chain_scan_execution, scan_instance: scan_instance, account: account, status: "running")
    end
    let!(:completed_execution) do
      create(:supply_chain_scan_execution, scan_instance: scan_instance, account: account, status: "completed")
    end
    let!(:failed_execution) do
      create(:supply_chain_scan_execution, scan_instance: scan_instance, account: account, status: "failed")
    end
    let!(:cancelled_execution) do
      create(:supply_chain_scan_execution, scan_instance: scan_instance, account: account, status: "cancelled")
    end
    let!(:manual_execution) do
      create(:supply_chain_scan_execution, scan_instance: scan_instance, account: account, trigger_type: "manual")
    end
    let!(:scheduled_execution) do
      create(:supply_chain_scan_execution, scan_instance: scan_instance, account: account, trigger_type: "scheduled")
    end
    let!(:webhook_execution) do
      create(:supply_chain_scan_execution, scan_instance: scan_instance, account: account, trigger_type: "webhook")
    end
    let!(:pipeline_execution) do
      create(:supply_chain_scan_execution, scan_instance: scan_instance, account: account, trigger_type: "pipeline")
    end
    let!(:api_execution) do
      create(:supply_chain_scan_execution, scan_instance: scan_instance, account: account, trigger_type: "api")
    end
    let!(:another_instance_execution) do
      another_instance = create(:supply_chain_scan_instance, account: account)
      create(:supply_chain_scan_execution, scan_instance: another_instance, account: account)
    end

    describe "#by_status" do
      it "filters executions by status" do
        expect(described_class.by_status("pending")).to include(pending_execution)
        expect(described_class.by_status("pending")).not_to include(completed_execution)
      end
    end

    describe "#pending" do
      it "returns only pending executions" do
        expect(described_class.pending).to include(pending_execution)
        expect(described_class.pending).not_to include(running_execution, completed_execution)
      end
    end

    describe "#running" do
      it "returns only running executions" do
        expect(described_class.running).to include(running_execution)
        expect(described_class.running).not_to include(pending_execution, completed_execution)
      end
    end

    describe "#completed" do
      it "returns only completed executions" do
        expect(described_class.completed).to include(completed_execution)
        expect(described_class.completed).not_to include(pending_execution, failed_execution)
      end
    end

    describe "#failed" do
      it "returns only failed executions" do
        expect(described_class.failed).to include(failed_execution)
        expect(described_class.failed).not_to include(pending_execution, completed_execution)
      end
    end

    describe "#cancelled" do
      it "returns only cancelled executions" do
        expect(described_class.cancelled).to include(cancelled_execution)
        expect(described_class.cancelled).not_to include(pending_execution, completed_execution)
      end
    end

    describe "#finished" do
      it "returns completed, failed, and cancelled executions" do
        expect(described_class.finished).to include(completed_execution, failed_execution, cancelled_execution)
        expect(described_class.finished).not_to include(pending_execution, running_execution)
      end
    end

    describe "#successful" do
      it "returns only successful (completed) executions" do
        expect(described_class.successful).to include(completed_execution)
        expect(described_class.successful).not_to include(failed_execution, pending_execution)
      end
    end

    describe "#by_trigger" do
      it "filters executions by trigger type" do
        expect(described_class.by_trigger("manual")).to include(manual_execution)
        expect(described_class.by_trigger("manual")).not_to include(scheduled_execution)
      end
    end

    describe "#manual" do
      it "returns only manually triggered executions" do
        expect(described_class.manual).to include(manual_execution)
        expect(described_class.manual).not_to include(scheduled_execution, webhook_execution)
      end
    end

    describe "#scheduled" do
      it "returns only scheduled executions" do
        expect(described_class.scheduled).to include(scheduled_execution)
        expect(described_class.scheduled).not_to include(manual_execution, webhook_execution)
      end
    end

    describe "#for_instance" do
      it "returns executions for a specific instance" do
        expect(described_class.for_instance(scan_instance.id)).to include(pending_execution, running_execution, completed_execution)
        expect(described_class.for_instance(scan_instance.id)).not_to include(another_instance_execution)
      end
    end

    describe "#recent" do
      it "returns executions ordered by created_at descending" do
        executions = described_class.recent
        expect(executions.first.created_at).to be >= executions.last.created_at
      end
    end
  end

  # ============================================
  # Callbacks
  # ============================================
  describe "callbacks" do
    describe "before_validation :generate_execution_id" do
      it "generates execution_id before validation on create" do
        execution = build(:supply_chain_scan_execution, scan_instance: scan_instance, account: account, execution_id: nil)
        expect(execution.execution_id).to be_nil

        execution.valid?

        expect(execution.execution_id).to be_present
        expect(execution.execution_id).to match(/^exec-\d{14}-[0-9a-f]{8}$/)
      end

      it "does not overwrite existing execution_id" do
        execution = build(:supply_chain_scan_execution, scan_instance: scan_instance, account: account, execution_id: "custom-id-123")
        execution.valid?

        expect(execution.execution_id).to eq("custom-id-123")
      end
    end

    describe "before_save :sanitize_jsonb_fields" do
      it "initializes input_data to empty hash if nil" do
        execution = build(:supply_chain_scan_execution, scan_instance: scan_instance, account: account, input_data: nil)
        execution.save!

        expect(execution.input_data).to eq({})
      end

      it "initializes output_data to empty hash if nil" do
        execution = build(:supply_chain_scan_execution, scan_instance: scan_instance, account: account, output_data: nil)
        execution.save!

        expect(execution.output_data).to eq({})
      end

      it "initializes metadata to empty hash if nil" do
        execution = build(:supply_chain_scan_execution, scan_instance: scan_instance, account: account, metadata: nil)
        execution.save!

        expect(execution.metadata).to eq({})
      end

      it "preserves existing JSONB values" do
        input = { "key" => "value" }
        output = { "result" => "success" }
        execution = build(:supply_chain_scan_execution, scan_instance: scan_instance, account: account, input_data: input, output_data: output)
        execution.save!
        execution.reload

        expect(execution.input_data).to eq(input)
        expect(execution.output_data).to eq(output)
      end
    end

    describe "after_save :update_instance_stats" do
      context "when status changes to completed" do
        it "calls update_instance_stats on the scan_instance" do
          execution = create(:supply_chain_scan_execution, scan_instance: scan_instance, account: account, status: "pending")
          allow(scan_instance).to receive(:record_execution_result!)

          execution.update!(status: "completed", completed_at: Time.current)

          expect(scan_instance).to have_received(:record_execution_result!).with(success: true)
        end
      end

      context "when status changes to failed" do
        it "calls update_instance_stats on the scan_instance" do
          execution = create(:supply_chain_scan_execution, scan_instance: scan_instance, account: account, status: "pending")
          allow(scan_instance).to receive(:record_execution_result!)

          execution.update!(status: "failed", completed_at: Time.current)

          expect(scan_instance).to have_received(:record_execution_result!).with(success: false)
        end
      end

      context "when status does not change" do
        it "does not call update_instance_stats" do
          execution = create(:supply_chain_scan_execution, scan_instance: scan_instance, account: account, status: "pending")
          allow(scan_instance).to receive(:record_execution_result!)

          execution.update!(logs: "new log entry")

          expect(scan_instance).not_to have_received(:record_execution_result!)
        end
      end
    end
  end

  # ============================================
  # Status Predicates
  # ============================================
  describe "status predicates" do
    describe "#pending?" do
      it "returns true when status is pending" do
        execution = build(:supply_chain_scan_execution, status: "pending")
        expect(execution.pending?).to be true
      end

      it "returns false when status is not pending" do
        execution = build(:supply_chain_scan_execution, status: "running")
        expect(execution.pending?).to be false
      end
    end

    describe "#running?" do
      it "returns true when status is running" do
        execution = build(:supply_chain_scan_execution, status: "running")
        expect(execution.running?).to be true
      end

      it "returns false when status is not running" do
        execution = build(:supply_chain_scan_execution, status: "pending")
        expect(execution.running?).to be false
      end
    end

    describe "#completed?" do
      it "returns true when status is completed" do
        execution = build(:supply_chain_scan_execution, status: "completed")
        expect(execution.completed?).to be true
      end

      it "returns false when status is not completed" do
        execution = build(:supply_chain_scan_execution, status: "pending")
        expect(execution.completed?).to be false
      end
    end

    describe "#failed?" do
      it "returns true when status is failed" do
        execution = build(:supply_chain_scan_execution, status: "failed")
        expect(execution.failed?).to be true
      end

      it "returns false when status is not failed" do
        execution = build(:supply_chain_scan_execution, status: "pending")
        expect(execution.failed?).to be false
      end
    end

    describe "#cancelled?" do
      it "returns true when status is cancelled" do
        execution = build(:supply_chain_scan_execution, status: "cancelled")
        expect(execution.cancelled?).to be true
      end

      it "returns false when status is not cancelled" do
        execution = build(:supply_chain_scan_execution, status: "pending")
        expect(execution.cancelled?).to be false
      end
    end

    describe "#finished?" do
      it "returns true when status is completed" do
        execution = build(:supply_chain_scan_execution, status: "completed")
        expect(execution.finished?).to be true
      end

      it "returns true when status is failed" do
        execution = build(:supply_chain_scan_execution, status: "failed")
        expect(execution.finished?).to be true
      end

      it "returns true when status is cancelled" do
        execution = build(:supply_chain_scan_execution, status: "cancelled")
        expect(execution.finished?).to be true
      end

      it "returns false when status is pending or running" do
        execution = build(:supply_chain_scan_execution, status: "pending")
        expect(execution.finished?).to be false

        execution = build(:supply_chain_scan_execution, status: "running")
        expect(execution.finished?).to be false
      end
    end

    describe "#successful?" do
      it "returns true when status is completed" do
        execution = build(:supply_chain_scan_execution, status: "completed")
        expect(execution.successful?).to be true
      end

      it "returns false when status is not completed" do
        execution = build(:supply_chain_scan_execution, status: "pending")
        expect(execution.successful?).to be false

        execution = build(:supply_chain_scan_execution, status: "failed")
        expect(execution.successful?).to be false
      end
    end
  end

  # ============================================
  # Trigger Type Predicates
  # ============================================
  describe "trigger type predicates" do
    describe "#manual?" do
      it "returns true when trigger_type is manual" do
        execution = build(:supply_chain_scan_execution, trigger_type: "manual")
        expect(execution.manual?).to be true
      end

      it "returns false when trigger_type is not manual" do
        execution = build(:supply_chain_scan_execution, trigger_type: "scheduled")
        expect(execution.manual?).to be false
      end
    end

    describe "#scheduled?" do
      it "returns true when trigger_type is scheduled" do
        execution = build(:supply_chain_scan_execution, trigger_type: "scheduled")
        expect(execution.scheduled?).to be true
      end

      it "returns false when trigger_type is not scheduled" do
        execution = build(:supply_chain_scan_execution, trigger_type: "manual")
        expect(execution.scheduled?).to be false
      end
    end
  end

  # ============================================
  # Instance Methods - Formatting
  # ============================================
  describe "#formatted_duration" do
    it "returns nil when duration_ms is not present" do
      execution = build(:supply_chain_scan_execution, duration_ms: nil)
      expect(execution.formatted_duration).to be_nil
    end

    it "formats duration in seconds when less than a minute" do
      execution = build(:supply_chain_scan_execution, duration_ms: 45000)
      expect(execution.formatted_duration).to eq("45s")
    end

    it "formats duration in minutes and seconds when at least a minute" do
      execution = build(:supply_chain_scan_execution, duration_ms: 125000)
      expect(execution.formatted_duration).to eq("2m 5s")
    end

    it "formats duration correctly with zero seconds" do
      execution = build(:supply_chain_scan_execution, duration_ms: 120000)
      expect(execution.formatted_duration).to eq("2m 0s")
    end

    it "formats duration correctly with various values" do
      execution = build(:supply_chain_scan_execution, duration_ms: 5432)
      expect(execution.formatted_duration).to eq("5s")

      execution.duration_ms = 65000
      expect(execution.formatted_duration).to eq("1m 5s")
    end
  end

  # ============================================
  # Instance Methods - Status Transitions
  # ============================================
  describe "#start!" do
    it "updates status to running and sets started_at" do
      execution = create(:supply_chain_scan_execution, scan_instance: scan_instance, account: account, status: "pending", started_at: nil)

      expect {
        execution.start!
      }.to change {
        execution.reload.status
      }.from("pending").to("running")

      expect(execution.started_at).to be_present
    end

    it "raises error if execution is not found" do
      execution = create(:supply_chain_scan_execution, scan_instance: scan_instance, account: account)
      execution_id = execution.id
      execution.delete

      expect {
        SupplyChain::ScanExecution.find(execution_id).start!
      }.to raise_error(ActiveRecord::RecordNotFound)
    end
  end

  describe "#complete!" do
    it "updates status to completed and sets completed_at and duration_ms" do
      execution = create(:supply_chain_scan_execution, scan_instance: scan_instance, account: account, status: "running", started_at: 5.seconds.ago)

      expect {
        execution.complete!({ "result" => "success" })
      }.to change {
        execution.reload.status
      }.from("running").to("completed")

      expect(execution.completed_at).to be_present
      expect(execution.duration_ms).to be_present
      expect(execution.output_data).to eq({ "result" => "success" })
    end

    it "sets output_data to empty hash if not provided" do
      execution = create(:supply_chain_scan_execution, scan_instance: scan_instance, account: account, status: "running", started_at: 1.second.ago)
      execution.complete!

      expect(execution.output_data).to eq({})
    end

    it "calculates duration_ms from started_at and current time" do
      started = 5.seconds.ago
      execution = create(:supply_chain_scan_execution, scan_instance: scan_instance, account: account, status: "running", started_at: started)

      execution.complete!

      expect(execution.duration_ms).to be_a(Integer)
      expect(execution.duration_ms).to be > 0
    end
  end

  describe "#fail!" do
    it "updates status to failed and sets completed_at, duration_ms, and error_message" do
      execution = create(:supply_chain_scan_execution, scan_instance: scan_instance, account: account, status: "running", started_at: 3.seconds.ago)

      expect {
        execution.fail!("Connection timeout")
      }.to change {
        execution.reload.status
      }.from("running").to("failed")

      expect(execution.completed_at).to be_present
      expect(execution.duration_ms).to be_present
      expect(execution.error_message).to eq("Connection timeout")
    end

    it "preserves error message with special characters" do
      execution = create(:supply_chain_scan_execution, scan_instance: scan_instance, account: account, status: "running", started_at: 1.second.ago)
      error_msg = 'Error: "invalid JSON" @ line 42'

      execution.fail!(error_msg)

      expect(execution.error_message).to eq(error_msg)
    end
  end

  describe "#cancel!" do
    it "updates status to cancelled and sets completed_at and duration_ms" do
      execution = create(:supply_chain_scan_execution, scan_instance: scan_instance, account: account, status: "pending", started_at: 5.minutes.ago)

      expect {
        execution.cancel!
      }.to change {
        execution.reload.status
      }.from("pending").to("cancelled")

      expect(execution.completed_at).to be_present
      expect(execution.duration_ms).to be_present
    end

    it "calculates duration even if not started" do
      execution = create(:supply_chain_scan_execution, scan_instance: scan_instance, account: account, status: "pending", started_at: nil)
      execution.cancel!

      expect(execution.duration_ms).to be_nil
    end
  end

  # ============================================
  # Instance Methods - Logging
  # ============================================
  describe "#append_log" do
    it "appends timestamped message to logs" do
      execution = create(:supply_chain_scan_execution, scan_instance: scan_instance, account: account, logs: "")

      execution.append_log("Scan started")

      expect(execution.logs).to include("Scan started")
      expect(execution.logs).to match(/\[\d{4}-\d{2}-\d{2}T/)
    end

    it "appends to existing logs with newline" do
      execution = create(:supply_chain_scan_execution, scan_instance: scan_instance, account: account, logs: "Initial log")

      execution.append_log("Second log")

      expect(execution.logs).to include("Initial log")
      expect(execution.logs).to include("Second log")
      expect(execution.logs.split("\n").length).to eq(2)
    end

    it "handles empty initial logs" do
      execution = create(:supply_chain_scan_execution, scan_instance: scan_instance, account: account, logs: nil)

      execution.append_log("First message")

      expect(execution.logs).to include("First message")
      expect(execution.logs).not_to start_with("\n")
    end

    it "persists log entries" do
      execution = create(:supply_chain_scan_execution, scan_instance: scan_instance, account: account, logs: "")

      execution.append_log("Log entry 1")
      execution.reload

      expect(execution.logs).to include("Log entry 1")

      execution.append_log("Log entry 2")
      execution.reload

      expect(execution.logs).to include("Log entry 1")
      expect(execution.logs).to include("Log entry 2")
    end

    it "includes ISO8601 formatted timestamps" do
      execution = create(:supply_chain_scan_execution, scan_instance: scan_instance, account: account, logs: "")
      before_time = Time.current

      execution.append_log("Test message")

      after_time = Time.current
      log_content = execution.logs

      expect(log_content).to match(/\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}/)
    end
  end

  # ============================================
  # Instance Methods - References
  # ============================================
  describe "#template_name" do
    it "returns the scan template name" do
      execution = create(:supply_chain_scan_execution, scan_instance: scan_instance, account: account)

      expect(execution.template_name).to eq(scan_template.name)
    end
  end

  describe "#instance_name" do
    it "returns the scan instance name" do
      execution = create(:supply_chain_scan_execution, scan_instance: scan_instance, account: account)

      expect(execution.instance_name).to eq(scan_instance.name)
    end
  end

  # ============================================
  # Instance Methods - Summary Data
  # ============================================
  describe "#summary" do
    it "returns a hash with execution summary" do
      user = create(:user)
      execution = create(:supply_chain_scan_execution,
                        scan_instance: scan_instance,
                        account: account,
                        triggered_by: user,
                        status: "completed",
                        trigger_type: "manual",
                        started_at: 10.seconds.ago,
                        completed_at: Time.current,
                        duration_ms: 10000,
                        error_message: nil)

      summary = execution.summary

      expect(summary).to be_a(Hash)
      expect(summary[:id]).to eq(execution.id)
      expect(summary[:execution_id]).to eq(execution.execution_id)
      expect(summary[:scan_instance_id]).to eq(scan_instance.id)
      expect(summary[:instance_name]).to eq(scan_instance.name)
      expect(summary[:template_name]).to eq(scan_template.name)
      expect(summary[:status]).to eq("completed")
      expect(summary[:trigger_type]).to eq("manual")
      expect(summary[:triggered_by_id]).to eq(user.id)
      expect(summary[:started_at]).to eq(execution.started_at)
      expect(summary[:completed_at]).to eq(execution.completed_at)
      expect(summary[:duration_ms]).to eq(10000)
      expect(summary[:formatted_duration]).to eq("10s")
      expect(summary[:successful]).to be true
      expect(summary[:error_message]).to be_nil
      expect(summary[:created_at]).to eq(execution.created_at)
    end

    it "includes error message when execution failed" do
      execution = create(:supply_chain_scan_execution,
                        scan_instance: scan_instance,
                        account: account,
                        status: "failed",
                        error_message: "Scan failed due to network error")

      summary = execution.summary

      expect(summary[:status]).to eq("failed")
      expect(summary[:successful]).to be false
      expect(summary[:error_message]).to eq("Scan failed due to network error")
    end

    it "handles nil triggered_by" do
      execution = create(:supply_chain_scan_execution,
                        scan_instance: scan_instance,
                        account: account,
                        triggered_by: nil)

      summary = execution.summary

      expect(summary[:triggered_by_id]).to be_nil
    end
  end

  describe "#detailed_execution" do
    it "returns comprehensive execution details" do
      execution = create(:supply_chain_scan_execution,
                        scan_instance: scan_instance,
                        account: account,
                        input_data: { "target" => "example.com" },
                        output_data: { "vulnerabilities" => [] },
                        logs: "Scan completed successfully",
                        status: "completed")

      detailed = execution.detailed_execution

      expect(detailed).to be_a(Hash)
      expect(detailed[:summary]).to be_a(Hash)
      expect(detailed[:input_data]).to eq({ "target" => "example.com" })
      expect(detailed[:output_data]).to eq({ "vulnerabilities" => [] })
      expect(detailed[:logs]).to eq("Scan completed successfully")
    end

    it "includes complete summary in detailed_execution" do
      execution = create(:supply_chain_scan_execution, scan_instance: scan_instance, account: account)

      detailed = execution.detailed_execution

      expect(detailed[:summary]).to include(:id, :execution_id, :status, :trigger_type)
    end
  end

  # ============================================
  # Private Methods (indirectly tested)
  # ============================================
  describe "private methods" do
    describe "generate_execution_id" do
      it "generates unique execution IDs" do
        execution1 = create(:supply_chain_scan_execution, scan_instance: scan_instance, account: account)
        execution2 = create(:supply_chain_scan_execution, scan_instance: scan_instance, account: account)

        expect(execution1.execution_id).not_to eq(execution2.execution_id)
      end

      it "generates execution ID with correct format" do
        # Build without letting factory set execution_id, then trigger callback
        execution = build(:supply_chain_scan_execution, scan_instance: scan_instance, account: account, execution_id: nil)
        execution.send(:generate_execution_id)

        # Format: exec-YYYYMMDDHHmmss-XXXXXXXX
        expect(execution.execution_id).to match(/^exec-\d{14}-[0-9a-f]{8}$/)
      end

      it "includes proper timestamp in execution ID" do
        travel_to Time.zone.local(2024, 1, 15, 10, 30, 45) do
          execution = build(:supply_chain_scan_execution, scan_instance: scan_instance, account: account, execution_id: nil)
          execution.send(:generate_execution_id)

          expect(execution.execution_id).to include("20240115103045")
        end
      end
    end

    describe "sanitize_jsonb_fields" do
      it "sets default empty hashes for JSONB fields" do
        execution = create(:supply_chain_scan_execution,
                          scan_instance: scan_instance,
                          account: account,
                          input_data: nil,
                          output_data: nil,
                          metadata: nil)

        expect(execution.input_data).to eq({})
        expect(execution.output_data).to eq({})
        expect(execution.metadata).to eq({})
      end
    end

    describe "calculate_duration" do
      it "calculates duration in milliseconds" do
        started = 5.seconds.ago
        execution = create(:supply_chain_scan_execution,
                          scan_instance: scan_instance,
                          account: account,
                          status: "running",
                          started_at: started)

        execution.complete!

        expect(execution.duration_ms).to be_a(Integer)
        expect(execution.duration_ms).to be >= 5000
      end

      it "returns nil if started_at is not set" do
        execution = create(:supply_chain_scan_execution,
                          scan_instance: scan_instance,
                          account: account,
                          status: "pending",
                          started_at: nil)

        execution.cancel!

        expect(execution.duration_ms).to be_nil
      end
    end

    describe "update_instance_stats" do
      it "calls record_execution_result when status changes to finished" do
        allow(scan_instance).to receive(:record_execution_result!)

        execution = create(:supply_chain_scan_execution,
                          scan_instance: scan_instance,
                          account: account,
                          status: "pending")

        execution.update!(status: "completed", completed_at: Time.current)

        expect(scan_instance).to have_received(:record_execution_result!).with(success: true)
      end

      it "passes success true when status is completed" do
        allow(scan_instance).to receive(:record_execution_result!)

        execution = create(:supply_chain_scan_execution,
                          scan_instance: scan_instance,
                          account: account,
                          status: "pending")

        execution.update!(status: "completed", completed_at: Time.current)

        expect(scan_instance).to have_received(:record_execution_result!).with(success: true)
      end

      it "passes success false when status is failed or cancelled" do
        allow(scan_instance).to receive(:record_execution_result!)

        execution = create(:supply_chain_scan_execution,
                          scan_instance: scan_instance,
                          account: account,
                          status: "pending")

        execution.update!(status: "failed", completed_at: Time.current)

        expect(scan_instance).to have_received(:record_execution_result!).with(success: false)
      end

      it "does not call record_execution_result for non-finished statuses" do
        allow(scan_instance).to receive(:record_execution_result!)

        execution = create(:supply_chain_scan_execution,
                          scan_instance: scan_instance,
                          account: account,
                          status: "pending")

        execution.update!(logs: "Added log entry")

        expect(scan_instance).not_to have_received(:record_execution_result!)
      end
    end
  end

  # ============================================
  # Integration Tests
  # ============================================
  describe "execution lifecycle" do
    it "supports complete execution flow" do
      execution = create(:supply_chain_scan_execution,
                        scan_instance: scan_instance,
                        account: account,
                        status: "pending",
                        trigger_type: "manual",
                        triggered_by: triggered_by_user)

      expect(execution).to be_pending

      execution.start!
      expect(execution).to be_running
      expect(execution.started_at).to be_present

      execution.append_log("Processing scan...")
      expect(execution.logs).to include("Processing scan...")

      execution.complete!({ "result" => "success" })
      expect(execution).to be_completed
      expect(execution).to be_successful
      expect(execution.completed_at).to be_present
      expect(execution.duration_ms).to be_present

      summary = execution.summary
      expect(summary[:successful]).to be true
      expect(summary[:status]).to eq("completed")
    end

    it "supports failed execution flow" do
      execution = create(:supply_chain_scan_execution,
                        scan_instance: scan_instance,
                        account: account,
                        status: "pending")

      execution.start!
      expect(execution).to be_running

      execution.append_log("Error occurred")
      execution.fail!("Scan failed: Network timeout")

      expect(execution).to be_failed
      expect(execution).not_to be_successful
      expect(execution.error_message).to eq("Scan failed: Network timeout")

      summary = execution.summary
      expect(summary[:successful]).to be false
    end

    it "supports cancelled execution flow" do
      execution = create(:supply_chain_scan_execution,
                        scan_instance: scan_instance,
                        account: account,
                        status: "pending")

      execution.cancel!

      expect(execution).to be_cancelled
      expect(execution).to be_finished
      expect(execution.completed_at).to be_present
    end
  end

  describe "execution with different trigger types" do
    it "supports manual trigger" do
      execution = create(:supply_chain_scan_execution,
                        scan_instance: scan_instance,
                        account: account,
                        trigger_type: "manual",
                        triggered_by: triggered_by_user)

      expect(execution).to be_manual
      expect(execution.triggered_by).to eq(triggered_by_user)
    end

    it "supports scheduled trigger" do
      execution = create(:supply_chain_scan_execution,
                        scan_instance: scan_instance,
                        account: account,
                        trigger_type: "scheduled",
                        triggered_by: nil)

      expect(execution).to be_scheduled
      expect(execution.triggered_by).to be_nil
    end

    it "supports webhook trigger" do
      execution = create(:supply_chain_scan_execution,
                        scan_instance: scan_instance,
                        account: account,
                        trigger_type: "webhook")

      expect(execution.trigger_type).to eq("webhook")
    end

    it "supports pipeline trigger" do
      execution = create(:supply_chain_scan_execution,
                        scan_instance: scan_instance,
                        account: account,
                        trigger_type: "pipeline")

      expect(execution.trigger_type).to eq("pipeline")
    end

    it "supports api trigger" do
      execution = create(:supply_chain_scan_execution,
                        scan_instance: scan_instance,
                        account: account,
                        trigger_type: "api")

      expect(execution.trigger_type).to eq("api")
    end
  end

  describe "execution with input/output data" do
    it "stores and retrieves input data" do
      input_data = {
        "target" => "https://example.com",
        "scan_type" => "full",
        "timeout" => 300
      }
      execution = create(:supply_chain_scan_execution,
                        scan_instance: scan_instance,
                        account: account,
                        input_data: input_data)

      expect(execution.input_data).to eq(input_data)
    end

    it "stores and retrieves output data" do
      output_data = {
        "vulnerabilities" => 5,
        "score" => 78,
        "status" => "completed"
      }
      execution = create(:supply_chain_scan_execution,
                        scan_instance: scan_instance,
                        account: account,
                        output_data: output_data)

      expect(execution.output_data).to eq(output_data)
    end

    it "updates output data on completion" do
      execution = create(:supply_chain_scan_execution,
                        scan_instance: scan_instance,
                        account: account,
                        status: "running",
                        started_at: 1.second.ago)

      execution.complete!({ "vulnerabilities" => 3, "status" => "success" })

      expect(execution.output_data).to eq({ "vulnerabilities" => 3, "status" => "success" })
    end
  end

  describe "uniqueness constraints" do
    it "enforces unique execution_id" do
      execution1 = create(:supply_chain_scan_execution, scan_instance: scan_instance, account: account)

      expect {
        create(:supply_chain_scan_execution,
               scan_instance: scan_instance,
               account: account,
               execution_id: execution1.execution_id)
      }.to raise_error(ActiveRecord::RecordInvalid)
    end
  end

  describe "account association" do
    it "requires account association" do
      execution = build(:supply_chain_scan_execution, scan_instance: scan_instance, account: nil)

      expect {
        execution.save!
      }.to raise_error(ActiveRecord::RecordInvalid)
    end

    it "belongs to correct account" do
      another_account = create(:account)
      execution = create(:supply_chain_scan_execution, scan_instance: scan_instance, account: account)

      expect(execution.account).to eq(account)
      expect(execution.account).not_to eq(another_account)
    end
  end
end
