# frozen_string_literal: true

require "rails_helper"

RSpec.describe SupplyChain::SigningKey, type: :model do
  let(:account) { create(:account) }
  let(:user) { create(:user, account: account) }

  describe "associations" do
    it { is_expected.to belong_to(:account) }
    it { is_expected.to belong_to(:created_by).class_name("User").optional }
    it { is_expected.to belong_to(:rotated_from).class_name("SupplyChain::SigningKey").optional }
    it { is_expected.to have_many(:rotated_to).class_name("SupplyChain::SigningKey").dependent(:nullify) }
    it { is_expected.to have_many(:attestations).class_name("SupplyChain::Attestation").dependent(:nullify) }
  end

  describe "validations" do
    subject do
      build(:supply_chain_signing_key,
            account: account,
            key_type: "cosign",
            name: "Test Key",
            public_key: SecureRandom.hex(64),
            status: "active")
    end

    it { is_expected.to validate_presence_of(:key_type) }
    it { is_expected.to validate_inclusion_of(:key_type).in_array(SupplyChain::SigningKey::KEY_TYPES) }
    it { is_expected.to validate_presence_of(:name) }
    it { is_expected.to validate_presence_of(:public_key) }
    it { is_expected.to validate_presence_of(:status) }
    it { is_expected.to validate_inclusion_of(:status).in_array(SupplyChain::SigningKey::STATUSES) }

    # Note: key_id and fingerprint are auto-generated by callbacks,
    # so we test their presence through callback tests instead of validation matchers

    describe "KMS validation" do
      it "requires kms_provider for kms_reference type" do
        key = build(:supply_chain_signing_key, account: account, key_type: "kms_reference", kms_provider: nil, kms_key_uri: "arn:aws:kms:...")
        expect(key).not_to be_valid
        expect(key.errors[:kms_provider]).to include("is required for KMS reference keys")
      end

      it "requires kms_key_uri for kms_reference type" do
        key = build(:supply_chain_signing_key, account: account, key_type: "kms_reference", kms_provider: "aws_kms", kms_key_uri: nil)
        expect(key).not_to be_valid
        expect(key.errors[:kms_key_uri]).to include("is required for KMS reference keys")
      end

      it "allows nil kms_provider for non-KMS types" do
        key = build(:supply_chain_signing_key, account: account, key_type: "cosign", kms_provider: nil)
        expect(key).to be_valid
      end
    end
  end

  describe "scopes" do
    let!(:active_key) { create(:supply_chain_signing_key, account: account, status: "active") }
    let!(:revoked_key) { create(:supply_chain_signing_key, account: account, status: "revoked") }
    let!(:expired_key) { create(:supply_chain_signing_key, account: account, status: "expired") }
    let!(:cosign_key) { create(:supply_chain_signing_key, account: account, key_type: "cosign") }
    let!(:gpg_key) { create(:supply_chain_signing_key, account: account, key_type: "gpg") }
    let!(:expiring_key) { create(:supply_chain_signing_key, account: account, expires_at: 15.days.from_now) }
    let!(:not_expiring_key) { create(:supply_chain_signing_key, account: account, expires_at: 60.days.from_now) }
    let!(:already_expired) { create(:supply_chain_signing_key, account: account, expires_at: 1.day.ago, status: "expired") }

    it "filters active keys" do
      expect(described_class.active).to include(active_key)
      expect(described_class.active).not_to include(revoked_key, expired_key)
    end

    it "filters by type" do
      expect(described_class.by_type("cosign")).to include(cosign_key)
      expect(described_class.by_type("cosign")).not_to include(gpg_key)
    end

    it "filters cosign keys" do
      expect(described_class.cosign_keys).to include(cosign_key)
      expect(described_class.cosign_keys).not_to include(gpg_key)
    end

    it "filters expiring_soon keys" do
      expect(described_class.expiring_soon(30)).to include(expiring_key)
      expect(described_class.expiring_soon(30)).not_to include(not_expiring_key)
    end

    it "filters expired keys" do
      expect(described_class.expired).to include(already_expired)
      expect(described_class.expired).not_to include(not_expiring_key)
    end

    it "filters not_expired keys" do
      expect(described_class.not_expired).to include(not_expiring_key)
      expect(described_class.not_expired).not_to include(already_expired)
    end
  end

  describe "status predicates" do
    it "#active? returns true for active status" do
      key = build(:supply_chain_signing_key, status: "active")
      expect(key.active?).to be true
    end

    it "#rotating? returns true for rotating status" do
      key = build(:supply_chain_signing_key, status: "rotating")
      expect(key.rotating?).to be true
    end

    it "#rotated? returns true for rotated status" do
      key = build(:supply_chain_signing_key, status: "rotated")
      expect(key.rotated?).to be true
    end

    it "#revoked? returns true for revoked status" do
      key = build(:supply_chain_signing_key, status: "revoked")
      expect(key.revoked?).to be true
    end

    it "#expired? returns true for expired status" do
      key = build(:supply_chain_signing_key, status: "expired")
      expect(key.expired?).to be true
    end

    it "#expired? returns true when expires_at is in the past" do
      key = build(:supply_chain_signing_key, status: "active", expires_at: 1.day.ago)
      expect(key.expired?).to be true
    end
  end

  describe "key type predicates" do
    it "#cosign? returns true for cosign type" do
      key = build(:supply_chain_signing_key, key_type: "cosign")
      expect(key.cosign?).to be true
    end

    it "#kms? returns true for kms_reference type" do
      key = build(:supply_chain_signing_key, key_type: "kms_reference")
      expect(key.kms?).to be true
    end

    it "#oidc? returns true for oidc_identity type" do
      key = build(:supply_chain_signing_key, key_type: "oidc_identity")
      expect(key.oidc?).to be true
    end

    it "#gpg? returns true for gpg type" do
      key = build(:supply_chain_signing_key, key_type: "gpg")
      expect(key.gpg?).to be true
    end
  end

  describe "#can_sign?" do
    it "returns true when active and not expired" do
      key = build(:supply_chain_signing_key, status: "active", expires_at: 30.days.from_now)
      expect(key.can_sign?).to be true
    end

    it "returns false when not active" do
      key = build(:supply_chain_signing_key, status: "revoked")
      expect(key.can_sign?).to be false
    end

    it "returns false when expired" do
      key = build(:supply_chain_signing_key, status: "active", expires_at: 1.day.ago)
      expect(key.can_sign?).to be false
    end
  end

  describe "#has_private_key?" do
    it "returns true when encrypted_private_key is present" do
      key = build(:supply_chain_signing_key, encrypted_private_key: "encrypted_data")
      expect(key.has_private_key?).to be true
    end

    it "returns true when kms_key_uri is present" do
      key = build(:supply_chain_signing_key, kms_key_uri: "arn:aws:kms:...")
      expect(key.has_private_key?).to be true
    end

    it "returns false when neither is present" do
      key = build(:supply_chain_signing_key, encrypted_private_key: nil, kms_key_uri: nil)
      expect(key.has_private_key?).to be false
    end
  end

  describe "#expiring_soon?" do
    it "returns true when expires_at is within days threshold" do
      key = build(:supply_chain_signing_key, expires_at: 15.days.from_now)
      expect(key.expiring_soon?(30)).to be true
    end

    it "returns false when expires_at is beyond threshold" do
      key = build(:supply_chain_signing_key, expires_at: 45.days.from_now)
      expect(key.expiring_soon?(30)).to be false
    end

    it "returns false when no expiry set" do
      key = build(:supply_chain_signing_key, expires_at: nil)
      expect(key.expiring_soon?).to be false
    end
  end

  describe "#days_until_expiration" do
    it "returns days until expiry" do
      key = build(:supply_chain_signing_key, expires_at: 30.days.from_now)
      expect(key.days_until_expiration).to be_within(1).of(30)
    end

    it "returns nil when no expiry" do
      key = build(:supply_chain_signing_key, expires_at: nil)
      expect(key.days_until_expiration).to be_nil
    end
  end

  describe "#rotate!" do
    let(:old_key) { create(:supply_chain_signing_key, account: account, status: "active") }
    let(:new_key) { build(:supply_chain_signing_key, account: account, status: "active") }

    it "sets old key status to rotated" do
      old_key.rotate!(new_key)
      expect(old_key.status).to eq("rotated")
    end

    it "records rotated_at timestamp" do
      old_key.rotate!(new_key)
      expect(old_key.rotated_at).to be_present
    end

    it "links new key to old key" do
      old_key.rotate!(new_key)
      expect(new_key.rotated_from).to eq(old_key)
    end

    it "saves the new key" do
      result = old_key.rotate!(new_key)
      expect(result).to be_persisted
    end
  end

  describe "#revoke!" do
    let(:key) { create(:supply_chain_signing_key, account: account, status: "active") }

    it "sets status to revoked" do
      key.revoke!
      expect(key.status).to eq("revoked")
    end
  end

  describe "#sign" do
    let(:key) { create(:supply_chain_signing_key, account: account, status: "active", key_type: "cosign") }

    it "returns nil when key cannot sign" do
      key.update!(status: "revoked")
      expect(key.sign("data")).to be_nil
    end

    it "raises error for unsupported key types" do
      key.update!(key_type: "oidc_identity")
      expect { key.sign("data") }.to raise_error(NotImplementedError)
    end
  end

  describe "#verify" do
    let(:key) { create(:supply_chain_signing_key, account: account, key_type: "cosign") }

    it "raises error for unsupported key types" do
      key.update!(key_type: "oidc_identity")
      expect { key.verify("data", "signature") }.to raise_error(NotImplementedError)
    end
  end

  describe "#summary" do
    let(:key) { create(:supply_chain_signing_key, account: account) }

    it "returns expected keys" do
      summary = key.summary

      expect(summary).to include(
        :id,
        :key_id,
        :key_type,
        :name,
        :fingerprint,
        :status,
        :can_sign,
        :expires_at,
        :days_until_expiration,
        :created_at
      )
    end
  end

  describe "callbacks" do
    describe "generate_key_id" do
      it "auto-generates key_id on create" do
        key = build(:supply_chain_signing_key, account: account, key_id: nil)
        key.save!
        expect(key.key_id).to match(/^key-[a-f0-9]+$/)
      end

      it "does not override existing key_id" do
        key = build(:supply_chain_signing_key, account: account, key_id: "my-custom-key")
        key.save!
        expect(key.key_id).to eq("my-custom-key")
      end
    end

    describe "calculate_fingerprint" do
      it "calculates SHA256 fingerprint from public key" do
        public_key = "test-public-key-data"
        key = build(:supply_chain_signing_key, account: account, public_key: public_key, fingerprint: nil)
        key.save!
        expect(key.fingerprint).to eq(Digest::SHA256.hexdigest(public_key))
      end

      it "recalculates fingerprint when public key changes" do
        key = create(:supply_chain_signing_key, account: account)
        old_fingerprint = key.fingerprint

        key.update!(public_key: "new-public-key-data")
        expect(key.fingerprint).not_to eq(old_fingerprint)
      end
    end

    describe "check_expiration" do
      it "sets status to expired when expires_at is in the past" do
        key = create(:supply_chain_signing_key, account: account, status: "active", expires_at: 1.day.from_now)
        key.update!(expires_at: 1.day.ago)
        expect(key.status).to eq("expired")
      end
    end
  end

  describe "JSONB sanitization" do
    it "initializes metadata as empty hash" do
      key = create(:supply_chain_signing_key, account: account, metadata: nil)
      expect(key.metadata).to eq({})
    end
  end
end
