# frozen_string_literal: true

module SupplyChain
  class RemediationPrService
    attr_reader :plan, :repository, :user

    def initialize(plan:, repository:, user:)
      @plan = plan
      @repository = repository
      @user = user
    end

    def generate_pr
      validate_plan!
      validate_repository!

      branch_name = generate_branch_name
      pr_title = generate_pr_title
      pr_body = generate_pr_body

      # Create PR via Git API
      result = create_pull_request(
        branch_name: branch_name,
        title: pr_title,
        body: pr_body
      )

      if result[:success]
        plan.update!(generated_pr_url: result[:pr_url])
        {
          success: true,
          pr_url: result[:pr_url],
          pr_number: result[:pr_number],
          branch_name: branch_name
        }
      else
        { success: false, error: result[:error] || "Failed to create pull request" }
      end
    end

    private

    def validate_plan!
      unless plan.approved?
        raise ArgumentError, "Plan must be approved before generating a PR"
      end

      if plan.generated_pr_url.present?
        raise ArgumentError, "PR has already been generated for this plan"
      end
    end

    def validate_repository!
      unless repository&.persisted?
        raise ArgumentError, "No repository associated with this remediation plan"
      end

      unless repository.credential&.persisted?
        raise ArgumentError, "Repository has no valid Git credential configured"
      end
    end

    def generate_branch_name
      timestamp = Time.current.strftime("%Y%m%d%H%M%S")
      "remediation/#{plan.id[0..7]}-#{timestamp}"
    end

    def generate_pr_title
      vuln_count = plan.target_vulnerability_count
      upgrade_count = plan.upgrade_count

      if vuln_count > 0 && upgrade_count > 0
        "Security: Fix #{vuln_count} vulnerabilities with #{upgrade_count} dependency upgrades"
      elsif vuln_count > 0
        "Security: Address #{vuln_count} vulnerabilities"
      elsif upgrade_count > 0
        "Dependencies: #{upgrade_count} package upgrades"
      else
        "Security remediation plan ##{plan.id[0..7]}"
      end
    end

    def generate_pr_body
      sections = []

      sections << "## Summary"
      sections << ""
      sections << "This PR was automatically generated from remediation plan `#{plan.id}`."
      sections << ""

      if plan.target_vulnerabilities.any?
        sections << "## Vulnerabilities Addressed"
        sections << ""
        plan.target_vulnerabilities.each do |vuln|
          severity = vuln["severity"] || "unknown"
          vuln_id = vuln["vulnerability_id"] || vuln["cve_id"] || "Unknown"
          package = vuln["package_name"] || "N/A"
          sections << "- **#{vuln_id}** (#{severity}) - #{package}"
        end
        sections << ""
      end

      if plan.upgrade_recommendations.any?
        sections << "## Dependency Upgrades"
        sections << ""
        sections << "| Package | From | To | Breaking |"
        sections << "|---------|------|----|---------:|"
        plan.upgrade_recommendations.each do |upgrade|
          pkg = upgrade["package_name"]
          from = upgrade["current_version"] || "N/A"
          to = upgrade["target_version"] || "N/A"
          breaking = upgrade["is_breaking"] ? "⚠️ Yes" : "No"
          sections << "| #{pkg} | #{from} | #{to} | #{breaking} |"
        end
        sections << ""
      end

      if plan.has_breaking_changes?
        sections << "## ⚠️ Breaking Changes"
        sections << ""
        plan.breaking_changes.each do |change|
          pkg = change["package_name"]
          desc = change["description"] || "Breaking change detected"
          sections << "- **#{pkg}**: #{desc}"
        end
        sections << ""
      end

      sections << "---"
      sections << ""
      sections << "_Generated by Powernode Supply Chain Security_"
      sections << "_Plan confidence score: #{(plan.confidence_score * 100).round(1)}%_" if plan.confidence_score

      sections.join("\n")
    end

    def create_pull_request(branch_name:, title:, body:)
      client = git_client
      owner = repository.owner
      repo_name = repository.name
      base_branch = repository.default_branch || "main"

      client.create_pull_request(
        owner,
        repo_name,
        title: title,
        body: body,
        head: branch_name,
        base: base_branch,
        draft: false
      )
    rescue StandardError => e
      Rails.logger.error "Failed to create PR: #{e.message}"
      { success: false, error: e.message }
    end

    def git_client
      @git_client ||= begin
        credential = repository.credential
        case repository.provider
        when "github"
          Devops::Git::GithubApiClient.new(credential)
        when "gitlab"
          Devops::Git::GitlabApiClient.new(credential)
        when "bitbucket"
          Devops::Git::BitbucketApiClient.new(credential)
        else
          raise ArgumentError, "Unsupported Git provider: #{repository.provider}"
        end
      end
    end
  end
end
